#############################################################################
# Makefile for building: STL
# Generated by qmake (2.01a) (Qt 4.8.6) on: Mon May 4 09:00:47 2015
# Project:  STL.pro
# Template: app
# Command: /usr/local/bin/qmake -o Makefile STL.pro
#############################################################################

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = 
CFLAGS        = -pipe -mmacosx-version-min=10.7 -O2 -arch x86_64 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -mmacosx-version-min=10.7 -O2 -arch x86_64 -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Cellar/qt/4.8.6/mkspecs/unsupported/macx-clang-libc++ -I.
LINK          = clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -mmacosx-version-min=10.7 -arch x86_64
LIBS          = $(SUBLIBS)   -L/usr/local/Cellar/sqlite/3.8.9/lib -lsqlite3 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/local/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.7

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		cursor.cpp \
		connection.cpp \
		connectionpool.cpp \
		connectionfactory.cpp \
		sqlconnection.cpp \
		command.cpp \
		sqlcommand.cpp \
		sqlcursor.cpp \
		connectionpoolguard.cpp 
OBJECTS       = main.o \
		cursor.o \
		connection.o \
		connectionpool.o \
		connectionfactory.o \
		sqlconnection.o \
		command.o \
		sqlcommand.o \
		sqlcursor.o \
		connectionpoolguard.o
DIST          = /usr/local/Cellar/qt/4.8.6/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/4.8.6/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/release.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/x86_64.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/shared.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/lex.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/include_source_dir.prf \
		STL.pro
QMAKE_TARGET  = STL
DESTDIR       = 
TARGET        = STL

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-arch \
		x86_64 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: STL.pro  /usr/local/Cellar/qt/4.8.6/mkspecs/unsupported/macx-clang-libc++/qmake.conf /usr/local/Cellar/qt/4.8.6/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/4.8.6/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/release.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/x86_64.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/shared.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/lex.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile STL.pro
/usr/local/Cellar/qt/4.8.6/mkspecs/common/unix.conf:
/usr/local/Cellar/qt/4.8.6/mkspecs/common/mac.conf:
/usr/local/Cellar/qt/4.8.6/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt/4.8.6/mkspecs/common/gcc-base-macx.conf:
/usr/local/Cellar/qt/4.8.6/mkspecs/common/clang.conf:
/usr/local/Cellar/qt/4.8.6/mkspecs/qconfig.pri:
/usr/local/Cellar/qt/4.8.6/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/default_pre.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/release.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/x86_64.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/shared.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/warn_on.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/rez.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/sdk.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/resources.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/uic.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/yacc.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/lex.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -o Makefile STL.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/STL1.0.0 || $(MKDIR) .tmp/STL1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/STL1.0.0/ && (cd `dirname .tmp/STL1.0.0` && $(TAR) STL1.0.0.tar STL1.0.0 && $(COMPRESS) STL1.0.0.tar) && $(MOVE) `dirname .tmp/STL1.0.0`/STL1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/STL1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp account.h \
		typetraits.h \
		accounttype.h \
		datetimetz.h \
		datetime.h \
		customer.h \
		nullable.h \
		objectbuffer.h \
		mappingitem.h \
		mappingsequence.h \
		connection.h \
		command.h \
		cursor.h \
		fieldtype.h \
		connectionfactory.h \
		connectionpool.h \
		connectionpoolguard.h \
		objectreader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

cursor.o: cursor.cpp cursor.h \
		fieldtype.h \
		typetraits.h \
		datetime.h \
		datetimetz.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cursor.o cursor.cpp

connection.o: connection.cpp connection.h \
		command.h \
		cursor.h \
		fieldtype.h \
		typetraits.h \
		datetime.h \
		datetimetz.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o connection.o connection.cpp

connectionpool.o: connectionpool.cpp connectionpool.h \
		connection.h \
		command.h \
		cursor.h \
		fieldtype.h \
		typetraits.h \
		datetime.h \
		datetimetz.h \
		connectionfactory.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o connectionpool.o connectionpool.cpp

connectionfactory.o: connectionfactory.cpp connectionfactory.h \
		connection.h \
		command.h \
		cursor.h \
		fieldtype.h \
		typetraits.h \
		datetime.h \
		datetimetz.h \
		sqlconnection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o connectionfactory.o connectionfactory.cpp

sqlconnection.o: sqlconnection.cpp sqlconnection.h \
		connection.h \
		command.h \
		cursor.h \
		fieldtype.h \
		typetraits.h \
		datetime.h \
		datetimetz.h \
		sqlcommand.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sqlconnection.o sqlconnection.cpp

command.o: command.cpp command.h \
		cursor.h \
		fieldtype.h \
		typetraits.h \
		datetime.h \
		datetimetz.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o command.o command.cpp

sqlcommand.o: sqlcommand.cpp sqlcommand.h \
		command.h \
		cursor.h \
		fieldtype.h \
		typetraits.h \
		datetime.h \
		datetimetz.h \
		sqlcursor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sqlcommand.o sqlcommand.cpp

sqlcursor.o: sqlcursor.cpp sqlcursor.h \
		cursor.h \
		fieldtype.h \
		typetraits.h \
		datetime.h \
		datetimetz.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sqlcursor.o sqlcursor.cpp

connectionpoolguard.o: connectionpoolguard.cpp connectionpoolguard.h \
		connectionpool.h \
		connection.h \
		command.h \
		cursor.h \
		fieldtype.h \
		typetraits.h \
		datetime.h \
		datetimetz.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o connectionpoolguard.o connectionpoolguard.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

